apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-worker-cross-namespace
  namespace: {{ .Values.namespace.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.airflow.serviceAccount }}
    namespace: {{ .Values.airflow.namespace }}
roleRef:
  kind: Role
  name: airflow-worker-role
  apiGroup: rbac.authorization.k8s.io

