airflow:
  fernetKey: "fernetkey" # Update with a secure fernet key (32 url-safe base64-encoded bytes)

postgresql:
  auth:
    username: <username> # Update with username
    password: <password>  # Update with password
    database: airflow

webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: <username> # Update with username
    email: <email> # Update with email
    firstName: <firstName> # Update with first name
    lastName: <lastName> # Update with last name
    password: <password> # Update with password