# This file contains the secrets for Airflow. Update the values and save as secrets.yaml
fernetKey: "USE_A_STRONG_FERNET_KEY_HERE" # Generate with: openssl rand -base64 32
webserverSecretKey: "USE_A_LONG_RANDOM_STRING_HERE"
apiSecretKey: "A_VERY_LONG_RANDOM_STRING_64_CHARS" #Only used for airflow 3.x

postgresql:
  auth:
    username: <username> # Update with username
    password: <password>  # Update with
    postgresPassword: <postgres_password> # Update with postgres password (superuser password)
    database: <database name> # Update with database name

data:
  metadataConnection:
    db: <database name> # Update with database name

webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: <username> # Update with username
    email: <email> # Update with email
    firstName: <firstName> # Update with first name
    lastName: <lastName> # Update with last name
    password: <password> # Update with password